version: "3"

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
  mariadb:
    image: mariadb:10
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
    volumes:
      - ./db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
#  zookeeper:
#    image: wurstmeister/zookeeper
#    container_name: zookeeper
#    ports:
#      - "2181:2181"
#  kafka:
#    image: wurstmeister/kafka
#    container_name: kafka
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_ADVERTISED_HOST_NAME: localhost
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181


